/*
 * Copyright (c) 2021. Something Technology
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in allcopies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
import { schema } from 'avsc';
import RecordType = schema.RecordType;

export type SchemaConfig = {
  schema: RecordType;
  topicName: string;
};

export type KafkaTSConfig = {
  schemaConfigs: SchemaConfig[];
  clientId: string;
};

/**
 * we need any as long as our consume function is not prepared for generics generated by the registered schemes
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type KafkaMessageValue = any;

export type Headers = { [key: string]: string };

type ConsumeCallbackMessage<M> = {
  topic: string;
  message: M;
  headers?: Headers;
  timestamp: string;
};
export type SubscriptionCallback<M = KafkaMessageValue> = (
  msg: ConsumeCallbackMessage<M>
) => Promise<void>;
